name: Compile LaTeX PDF

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup LaTeX
      uses: dante-ev/latex-action@v2
      with:
        root_file: main.tex   # change this to your main .tex file
        latexmk_args: -pdf -interaction=nonstopmode

    - name: Move PDF to public folder
      run: |
        mkdir -p public
        mv main.pdf public/Resume_Sai_Manohar_Vemuri.pdf

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/Resume_Sai_Manohar_Vemuri.pdf
        git commit -m "Auto-update PDF from LaTeX" || echo "No changes to commit"
        git push
